---
github_repo: will-santiago/github-test
filenameLanguageSeparator: "~"

sourceLocale:
  key: en
  tms: en_us
  
locales:
- key: pt-BR
  tms: pt_br


sources:
- defaultOutputPathPattern: "{lang}/{filename}"
  filenameLanguageSeparator: "."
  sourceFiles:
  - path: en/NEWS01.json


